/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 20
   Tile set      : C:\Users\carlo\Desktop\Periodo 7\IHS\Projeto Pong\assets\map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 18
#define mapHeight 20
#define mapBank 0

extern unsigned char map[];

/* End of MAP.H */
