/*

 P1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\shk\Desktop\ihs\Pong\assets\gray.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define p1Width 20
#define p1Height 18
#define p1Bank 0

extern unsigned char p1[];

/* End of P1.H */
