/*

 P2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\shk\Desktop\ihs\Pong\assets\gray.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define p2Width 20
#define p2Height 18
#define p2Bank 0

extern unsigned char p2[];

/* End of P2.H */
